### ISSUE TITLE
Exception at .scrollToRowAtIndexPath

### ISSUE THREAD

**Issue by mbaldinazzo** [sandeeplearner/SO-Code#3]
.

**Comment by sandeeplearner** [comment]
try,

self.tableview.reloadData() tableview.scrollToRowAtIndexPath(NSIndexPath(forRow: (self.xLimit - 1), inSection: indexPath.section), atScrollPosition: .Bottom, animated: false)

**Comment by mbaldinazzo** [comment]
I tried your method but last cell in tableview isn't shown (the load more cell).
I tried also this method as suggested here:
[scrollToRowAtIndexPath](http://stackoverflow.com/questions/26244293/scrolltorowatindexpath-with-uitableview-does-not-work#29799626).
It seems work, what do you think?
